version: '3.8'

services:
  memory-palace-app:
    build: .
    expose:
      - "8080"
    volumes:
      # Persist database
      - memory_palace_data:/app/data
      # Persist uploaded images
      - memory_palace_uploads:/app/wwwroot/uploads
      # Optional: Persist logs
      - memory_palace_logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/memorypalace.db
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - memory-palace-network

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - memory-palace-network
    depends_on:
      - memory-palace-app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

networks:
  memory-palace-network:
    driver: bridge

volumes:
  memory_palace_data:
    driver: local
  memory_palace_uploads:
    driver: local
  memory_palace_logs:
    driver: local